#!/usr/bin/env python

"""Prototype support for PEP 518:

"Specifying Minimum Build System Requirements for Python Projects".

A future version of pip will do this for us and we'll remove this script.

This script installs Rasterio in develop mode (``pip install -e .[test]``).
"""

import subprocess


def main():

    # Parse config file for build system requirements.
    build_system_requirements = None
    with open('pyproject.toml') as config:
        for line in config:
            if line.startswith('requires'):
                build_system_requirements = line.split('=')[-1]

    # Install them if found.
    if build_system_requirements:
        reqs = eval(build_system_requirements)
        subprocess.call(['pip', 'install'] +  reqs)

    # Now install our package in editable mode.
    subprocess.call(['pip', 'install', '-e', '.[test]'] +  reqs)


if __name__ == '__main__':
    main()
