"""Type stubs for rasterio._base Cython module."""

from __future__ import annotations

from contextlib import ExitStack
from typing import Any, Iterator

from affine import Affine
from rasterio.control import GroundControlPoint
from rasterio.coords import BoundingBox
from rasterio.crs import CRS
from rasterio.enums import (
    ColorInterp,
    Compression,
    Interleaving,
    MaskFlags,
    PhotometricInterp,
)
from rasterio.profiles import Profile
from rasterio.rpc import RPC
from rasterio.windows import Window

class DatasetBase:
    name: str | None
    mode: str
    options: dict[str, Any]
    driver: str
    width: int
    height: int
    shape: tuple[int, int]

    def __init__(
        self,
        path: Any = ...,
        driver: str | list[str] | None = ...,
        sharing: bool = ...,
        thread_safe: bool = ...,
        **kwargs: Any,
    ) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> DatasetBase: ...
    def __exit__(self, *exc_details: Any) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def closed(self) -> bool: ...
    @property
    def count(self) -> int: ...
    @property
    def indexes(self) -> tuple[int, ...]: ...
    @property
    def dtypes(self) -> tuple[str, ...]: ...
    @property
    def block_shapes(self) -> list[tuple[int, int]]: ...
    @property
    def nodatavals(self) -> tuple[float | None, ...]: ...
    @property
    def nodata(self) -> float | None: ...
    @nodata.setter
    def nodata(self, value: float | None) -> None: ...
    @property
    def mask_flag_enums(self) -> tuple[list[MaskFlags], ...]: ...
    @property
    def crs(self) -> CRS | None: ...
    @crs.setter
    def crs(self, value: Any) -> None: ...
    @property
    def descriptions(self) -> tuple[str | None, ...]: ...
    @descriptions.setter
    def descriptions(self, value: tuple[str | None, ...]) -> None: ...
    @property
    def transform(self) -> Affine: ...
    @transform.setter
    def transform(self, value: Affine) -> None: ...
    @property
    def offsets(self) -> tuple[float, ...]: ...
    @offsets.setter
    def offsets(self, value: tuple[float, ...]) -> None: ...
    @property
    def scales(self) -> tuple[float, ...]: ...
    @scales.setter
    def scales(self, value: tuple[float, ...]) -> None: ...
    @property
    def units(self) -> tuple[str | None, ...]: ...
    @units.setter
    def units(self, value: tuple[str | None, ...]) -> None: ...
    def block_window(self, bidx: int, i: int, j: int) -> Window: ...
    def block_size(self, bidx: int, i: int, j: int) -> int: ...
    def block_windows(
        self, bidx: int = ...,
    ) -> Iterator[tuple[tuple[int, int], Window]]: ...
    @property
    def bounds(self) -> BoundingBox: ...
    @property
    def res(self) -> tuple[float, float]: ...
    @property
    def meta(self) -> dict[str, Any]: ...
    @property
    def compression(self) -> Compression | str | None: ...
    @property
    def interleaving(self) -> Interleaving | None: ...
    @property
    def photometric(self) -> PhotometricInterp | None: ...
    @property
    def is_tiled(self) -> bool: ...
    @property
    def profile(self) -> Profile: ...
    def lnglat(self) -> tuple[float, float]: ...
    @property
    def subdatasets(self) -> list[str]: ...
    def tag_namespaces(self, bidx: int = ...) -> list[str]: ...
    def tags(self, bidx: int = ..., ns: str | None = ...) -> dict[str, str]: ...
    def get_tag_item(
        self,
        ns: str,
        dm: str | None = ...,
        bidx: int = ...,
        ovr: int | None = ...,
    ) -> str | None: ...
    @property
    def colorinterp(self) -> tuple[ColorInterp, ...]: ...
    @colorinterp.setter
    def colorinterp(self, value: tuple[ColorInterp, ...]) -> None: ...
    def colormap(self, bidx: int) -> dict[int, tuple[int, int, int, int]]: ...
    def overviews(self, bidx: int) -> list[int]: ...
    def checksum(self, bidx: int, window: Window | None = ...) -> int: ...
    @property
    def gcps(self) -> tuple[list[GroundControlPoint], CRS | None]: ...
    @gcps.setter
    def gcps(
        self, value: tuple[list[GroundControlPoint], CRS | None]
    ) -> None: ...
    @property
    def rpcs(self) -> RPC | None: ...
    @rpcs.setter
    def rpcs(self, value: RPC) -> None: ...
    @property
    def files(self) -> list[str]: ...
    def read_crs(self) -> CRS | None: ...
    def read_transform(self) -> list[float]: ...
    def get_transform(self) -> list[float]: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...

def get_dataset_driver(path: Any) -> str: ...
def driver_supports_mode(drivername: str, creation_mode: str) -> bool: ...
def driver_can_create(drivername: str) -> bool: ...
def driver_can_create_copy(drivername: str) -> bool: ...
