"""Type stubs for rasterio.crs Cython module."""

from __future__ import annotations

from typing import Any, Iterator

class CRS:
    """A geographic or projected coordinate reference system."""

    def __init__(
        self, initialdata: dict[str, Any] | None = ..., **kwargs: Any
    ) -> None: ...
    @property
    def data(self) -> dict[str, Any]: ...
    @property
    def is_valid(self) -> bool: ...
    @property
    def is_epsg_code(self) -> bool: ...
    @property
    def wkt(self) -> str: ...
    @property
    def is_geographic(self) -> bool: ...
    @property
    def is_projected(self) -> bool: ...
    @property
    def linear_units(self) -> str: ...
    @property
    def linear_units_factor(self) -> tuple[str, float]: ...
    @property
    def units_factor(self) -> tuple[str, float]: ...
    @property
    def geodetic_crs(self) -> CRS: ...
    def to_dict(self, projjson: bool = ...) -> dict[str, Any]: ...
    def to_proj4(self) -> str: ...
    def to_wkt(
        self,
        morph_to_esri_dialect: bool = ...,
        version: str | None = ...,
    ) -> str: ...
    def to_epsg(self, confidence_threshold: int = ...) -> int | None: ...
    def to_authority(
        self, confidence_threshold: int = ...
    ) -> tuple[str, str] | None: ...
    def to_string(self) -> str: ...
    def equals(self, other: Any, ignore_axis_order: bool = ...) -> bool: ...
    @staticmethod
    def from_epsg(code: int | str) -> CRS: ...
    @staticmethod
    def from_proj4(proj: str) -> CRS: ...
    @staticmethod
    def from_dict(
        initialdata: dict[str, Any] | None = ..., **kwargs: Any
    ) -> CRS: ...
    @staticmethod
    def from_wkt(wkt: str, morph_from_esri_dialect: bool = ...) -> CRS: ...
    @staticmethod
    def from_user_input(
        value: Any, morph_from_esri_dialect: bool = ...
    ) -> CRS: ...
    @staticmethod
    def from_authority(auth_name: str, code: int | str) -> CRS: ...
    @staticmethod
    def from_string(
        value: str, morph_from_esri_dialect: bool = ...
    ) -> CRS: ...
    def get(self, item: str) -> Any: ...
    def items(self) -> Any: ...
    def __hash__(self) -> int: ...
    def __getitem__(self, item: str) -> Any: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __copy__(self) -> CRS: ...
    def __getstate__(self) -> str: ...
    def __setstate__(self, state: str) -> None: ...

def epsg_treats_as_latlong(input_crs: CRS | Any) -> bool: ...
def epsg_treats_as_northingeasting(input_crs: CRS | Any) -> bool: ...

all_proj_keys: set[str]
