#!/usr/bin/env python

"""Rasterio interactive dataset inspector"""

import argparse
import sys

import rasterio
from rasterio.tool import main

if __name__ == '__main__':

    parser = argparse.ArgumentParser(
        prog="rio_insp",
        description="Open a dataset and drop into an interactive interpreter")
    parser.add_argument(
        'src',
        metavar='FILE',
        help="Input dataset file name")
    args = parser.parse_args()

    sys.exit(
        main(
            'Rasterio %s Interactive Inspector (Python %s)\n'
            'Type "src.meta", "src.read_band(1)", or "help(src)" '
            'for more information.' %  (
                rasterio.__version__,
                '.'.join(map(str, sys.version_info[:3]))),
            args.src))

